[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "CPVI"
version = "0.2.0"
description = "Comprehensive Persian Verb Inflector (dual-mechanism, Words & Rules theory)"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Abbas Safardoost", email = "a.safardoust@gmail.com" }]
classifiers = [
    "Topic :: Text Processing",
    "Natural Language :: Persian",
    "Programming Language :: Python :: 3"
]

[project.urls]
Homepage = "https://github.com/asdoost/CPVI"
Repository = "https://github.com/asdoost/CPVI"
Issues = "https://github.com/asdoost/CPVI/issues"


[tool.setuptools]
packages = ["CPVI"]
include-package-data = false

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "build",
    "twine",
]

[tool.setuptools.package-data]
CPVI = ["data/*.json"]
